# Generated by Django 4.2 on 2023-04-11 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('warning', models.TextField(null=True)),
                ('company', models.CharField(max_length=255)),
                ('inventory', models.IntegerField()),
                ('imageSrc', models.SlugField(null=True)),
                ('weight', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPerscriptionPill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_pill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medb.pills')),
            ],
            options={
                'db_table': 'medb_user_prescription_pill',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1)),
                ('description', models.TextField(null=True)),
                ('birth_date', models.DateField()),
                ('imgSrc', models.SlugField(null=True)),
                ('prescription_pills', models.ManyToManyField(through='medb.UserPerscriptionPill', to='medb.pills')),
            ],
        ),
        migrations.AddField(
            model_name='userperscriptionpill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medb.users'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentText', models.TextField()),
                ('pill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medb.pills')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medb.users')),
            ],
        ),
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('soundSrc', models.SlugField()),
                ('time', models.TimeField(default='-')),
                ('taken', models.CharField(choices=[('P', 'Pending'), ('C', 'Complete'), ('F', 'Failed')], default='P', max_length=1)),
                ('day', models.ForeignKey(default='-', on_delete=django.db.models.deletion.PROTECT, to='medb.days')),
                ('user_prescription_pill', models.ForeignKey(default='-', on_delete=django.db.models.deletion.CASCADE, to='medb.userperscriptionpill')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='userperscriptionpill',
            unique_together={('user', 'per_pill')},
        ),
    ]
