# Generated by Django 4.2 on 2023-04-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pills',
            name='perscription',
            field=models.BooleanField(default=False),
        ),
    ]
