# Generated by Django 4.2 on 2023-04-13 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medb', '0002_pills_perscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarm',
            name='taken',
        ),
        migrations.CreateModel(
            name='Taken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken', models.BooleanField()),
                ('time_taken', models.DateTimeField(auto_now_add=True)),
                ('alarm', models.ForeignKey(default='-', on_delete=django.db.models.deletion.CASCADE, to='medb.alarm')),
            ],
        ),
    ]
