# Generated by Django 4.2 on 2023-04-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medb', '0005_rename_time_taken_taken_taken_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='prescription_pills',
            field=models.ManyToManyField(null=True, through='medb.UserPerscriptionPill', to='medb.pills'),
        ),
    ]
