# Generated by Django 4.2 on 2023-04-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medb', '0007_alter_users_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pills',
            name='weight',
            field=models.CharField(default='./pills/Acetaminophen.jpeg', max_length=255, null=True),
        ),
    ]
