# Generated by Django 4.2 on 2023-04-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medb', '0008_alter_pills_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pills',
            name='imageSrc',
            field=models.SlugField(default='./pills/Acetaminophen.jpeg', null=True),
        ),
        migrations.AlterField(
            model_name='pills',
            name='weight',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
