# Generated by Django 4.2 on 2023-04-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medb', '0009_alter_pills_imagesrc_alter_pills_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='soundSrc',
            field=models.SlugField(default='/Users/Desktop/Alarm.wav'),
        ),
    ]
