# Generated by Django 4.2 on 2023-04-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medb', '0010_alter_alarm_soundsrc'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default='-', max_length=255),
        ),
    ]
