# Generated by Django 4.2 on 2023-04-20 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medb', '0012_motor'),
    ]

    operations = [
        migrations.AddField(
            model_name='pills',
            name='motor',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='medb.motor'),
        ),
    ]
