# Generated by Django 4.2 on 2023-04-20 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medb', '0013_pills_motor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pills',
            name='motor',
        ),
    ]
