# Generated by Django 4.2 on 2023-04-20 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medb', '0014_remove_pills_motor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motor_Pill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medb.motor')),
                ('pill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medb.pills')),
            ],
        ),
    ]
