# Generated by Django 4.2 on 2023-04-20 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medb', '0015_motor_pill'),
    ]

    operations = [
        migrations.AddField(
            model_name='pills',
            name='motor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='medb.motor'),
        ),
        migrations.DeleteModel(
            name='Motor_Pill',
        ),
    ]
